# Generated by Django 3.1.2 on 2020-12-12 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tejidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partes', models.IntegerField()),
                ('temperatura', models.FloatField()),
                ('color', models.FloatField()),
                ('inflamacion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='grafo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conectado', models.BooleanField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='core.tejidos')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='core.tejidos')),
            ],
        ),
    ]
